name: appspector_flutter_app
description: An AppSpector Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sqflite: any
  path_provider: '>=0.4.1'
  http: '0.12.0'
  appspector: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
